### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'view'

### ISSUE THREAD

**Issue by hieuck** [kaibioinfo/ComfyUI_AdvancedRefluxControl#16]
!!! Exception during processing !!! 'NoneType' object has no attribute 'view'
Traceback (most recent call last):
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_AdvancedRefluxControl\nodes.py", line 220, in apply_stylemodel
    image, masko = prepareImageAndMask(clip_vision, image, mask, mode, autocrop_margin)
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_AdvancedRefluxControl\nodes.py", line 166, in prepareImageAndMask
    (bx,by,bx2,by2) = getBoundingBox(mask,W,H,autocrop_margin, desiredSize)
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_AdvancedRefluxControl\nodes.py", line 101, in getBoundingBox
    mask=mask.view(h,w)
AttributeError: 'NoneType' object has no attribute 'view'

**Comment by khengyun** [comment]
can you share your flow ?

**Comment by aswordok** [comment]
got prompt
Requested to load FluxClipModel_
loaded completely 9.5367431640625e+25 9319.23095703125 True
!!! Exception during processing !!! 'NoneType' object has no attribute 'view'
Traceback (most recent call last):
  File "D:\+AI\myComfyUI\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\myComfyUI\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\myComfyUI\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\+AI\myComfyUI\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\myComfyUI\ComfyUI\custom_nodes\ComfyUI_AdvancedRefluxControl\nodes.py", line 220, in apply_stylemodel
    image, masko = prepareImageAndMask(clip_vision, image, mask, mode, autocrop_margin)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\myComfyUI\ComfyUI\custom_nodes\ComfyUI_AdvancedRefluxControl\nodes.py", line 166, in prepareImageAndMask
    (bx,by,bx2,by2) = getBoundingBox(mask,W,H,autocrop_margin, desiredSize)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\myComfyUI\ComfyUI\custom_nodes\ComfyUI_AdvancedRefluxControl\nodes.py", line 101, in getBoundingBox
    mask=mask.view(h,w)
         ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'view'

Prompt executed in 3.53 seconds

![Image](https://github.com/user-attachments/assets/751924c1-b578-440c-a4dd-98719c1d1054)

**Comment by adydeejay** [comment]
Just create the mask for your image and connect it to ReduxAdvanced if you want to use "autocrop with mask" option.

![Image](https://github.com/user-attachments/assets/1e9ea0c9-551c-4c05-acb9-01b19fb79935)
